create sequence hibernate_sequence start 1 increment 1
create table cost_planning (id  bigserial not null, amount numeric(10, 2) not null, day int4, month int4, year int4, description varchar(255) not null, type varchar(255) not null, property_id int8 not null, primary key (id))
create table credit (id  bigserial not null, active boolean, capital numeric(19, 2) check (capital>=0), interest_rate_nominal_in_percent numeric(19, 2) check (interest_rate_nominal_in_percent>=0), name_of_institution varchar(255), redemption_at_begin_in_percent numeric(19, 2) check (redemption_at_begin_in_percent>=0), special_redemption_each_year_in_percent numeric(19, 2) check (special_redemption_each_year_in_percent>=0), primary key (id))
create table credit_aud (id int8 not null, rev int4 not null, revtype int2, active boolean, capital numeric(19, 2), interest_rate_nominal_in_percent numeric(19, 2), name_of_institution varchar(255), redemption_at_begin_in_percent numeric(19, 2), special_redemption_each_year_in_percent numeric(19, 2), primary key (id, rev))
create table forecast_configuration (id  bigserial not null, country_code varchar(255) not null, deprecation float8 not null, rental_increase float8 not null, rental_increase_frequence int4 not null, running_cost_index float8 not null, tax_quote float8 not null, primary key (id))
create table property (id  bigserial not null, city varchar(50) not null, country_code varchar(5) not null, street varchar(50) not null, street_number varchar(5) not null, zip varchar(255) not null, reconstruction numeric(19, 2) not null check (reconstruction>=0), renovation numeric(19, 2) not null check (renovation>=0), land_area_in_qm numeric(19, 2) not null check (land_area_in_qm>=0 AND land_area_in_qm<=10000), living_space_in_qm numeric(19, 2) not null check (living_space_in_qm>=1 AND living_space_in_qm<=10000), net_assets float8 not null check (net_assets>=0), no_apartments int8 not null check (no_apartments<=100 AND no_apartments>=1), no_parking int8 not null check (no_parking<=100 AND no_parking>=0), agency numeric(19, 2) not null check (agency>=0), court numeric(19, 2) not null check (court>=0), land_acquisition numeric(19, 2) not null check (land_acquisition>=0), notary numeric(19, 2) not null check (notary>=0), valuation numeric(19, 2) not null check (valuation>=0), purchase_date date, purchase_price numeric(19, 2) not null check (purchase_price<=10000000 AND purchase_price>=1), rental_net numeric(19, 2) not null check (rental_net>=0), administration_each_apartment numeric(19, 2) not null check (administration_each_apartment>=0), maintenance_each_qm numeric(19, 2) not null check (maintenance_each_qm>=0), status varchar(255) not null, type varchar(255) not null, year_of_construction int4 not null check (year_of_construction<=2100 AND year_of_construction>=1800), owner_id int8 not null, primary key (id))
create table property_aud (id int8 not null, rev int4 not null, revtype int2, city varchar(255), country_code varchar(255), street varchar(255), street_number varchar(255), zip varchar(255), reconstruction numeric(19, 2), renovation numeric(19, 2), land_area_in_qm numeric(19, 2), living_space_in_qm numeric(19, 2), net_assets float8, no_apartments int8, no_parking int8, agency numeric(19, 2), court numeric(19, 2), land_acquisition numeric(19, 2), notary numeric(19, 2), valuation numeric(19, 2), purchase_date date, purchase_price numeric(19, 2), rental_net numeric(19, 2), administration_each_apartment numeric(19, 2), maintenance_each_qm numeric(19, 2), status varchar(255), type varchar(255), year_of_construction int4, primary key (id, rev))
create table property_credit (property_id int8 not null, credit_id int8 not null, primary key (credit_id))
create table revinfo (rev int4 not null, revtstmp int8, primary key (rev))
create table user_role (id  bigserial not null, name varchar(255) not null, primary key (id))
create table users (id  bigserial not null, email varchar(255) not null, enabled boolean not null, password varchar(255) not null, user_name varchar(255) not null, primary key (id))
create table users_user_roles (user_id int8 not null, user_roles_id int8 not null)
alter table cost_planning add constraint UK_COST_PLANNING unique (year, month, day, property_id, type)
alter table forecast_configuration add constraint UK_l0rxoth3jpo1wdjey1vxm1s3d unique (country_code)
alter table cost_planning add constraint FKmgoc8xq8rg6qqjtskbuuwphij foreign key (property_id) references property
alter table credit_aud add constraint FKpabkjmbd9ephut6xcs0fwy47v foreign key (rev) references revinfo
alter table property add constraint FKqje3em0djsxgnxwy7klv6yju9 foreign key (owner_id) references users
alter table property_aud add constraint FKbax3qj40a4fxbpk03gaqswe57 foreign key (rev) references revinfo
alter table property_credit add constraint FKp2q6rr6opxrk6r2kt4rl5mct2 foreign key (property_id) references property
alter table property_credit add constraint FKrie9lx44ruwlaelmxr26wocp foreign key (credit_id) references credit
alter table users_user_roles add constraint FK_USER_TO_USER_ROLE foreign key (user_roles_id) references user_role
alter table users_user_roles add constraint FK_USER_ROLE_TO_USER foreign key (user_id) references users
